<?php

/**
 * @var \FlightLog\Application\Pilot\ViewModel\Pilot[]| array $members
 */

global $members, $user;
?>

<table class="liste">

    <tr>
        <th>#</th>
        <th>Prenom</th>
        <th>Nom</th>
    </tr>
    <?php foreach ($members as $member): ?>
        <tr class="pair">

            <?php if($user->rights->flightlog->pilot->edit): ?>
                <td><a href="<?php echo sprintf(DOL_URL_ROOT . '/flightlog/index.php?id=%s&r=%s', $member->getId(), 'edit_pilot'); ?>"><?php echo $member->getId(); ?></a></td>
            <?php endif; ?>

            <td><?php echo $member->getFirstname(); ?></td>
            <td><?php echo $member->getName(); ?></td>
            <td><?php echo img_picto($member->getReasons(), $member->getIconId(), '', false, false, false, '', 'classfortooltip') ?> </td>
        </tr>
    <?php endforeach; ?>
</table>
