<?php

/**
 * @var \FlightLog\Application\Pilot\ViewModel\Pilot[]| array $members
 */

global $members;
?>

<table class="liste">
<?php foreach($members as $member): ?>
    <tr class="pair">
        <td><a href="<?php echo sprintf(DOL_URL_ROOT.'/flightlog/index.php?id=%s&r=%s', $member->getId(), 'edit_pilot');?>"><?php echo $member->getId(); ?></a></td>
        <td><?php echo $member->getFirstname(); ?></td>
        <td><?php echo $member->getName(); ?></td>
    </tr>
<?php endforeach; ?>
</table>
