<?php

/**
 * @var \FlightLog\Application\Pilot\ViewModel\Pilot[]| array $members
 */

global $members, $user;
?>

<table class="liste">

    <tr>
        <th class="center">#</th>
        <th class="center">Prenom</th>
        <th class="center">Nom</th>
        <th class="center">N° de Licence</th>
        <th class="center">Qualifications - Groupe A</th>
        <th class="center">Qualifications - Gaz</th>
        <th class="center">Statut</th>
    </tr>
    <?php foreach ($members as $member): ?>
        <tr class="pair">

            <?php if($user->rights->flightlog->pilot->edit): ?>
                <td class="center"><a href="<?php echo sprintf(DOL_URL_ROOT . '/flightlog/index.php?id=%s&r=%s', $member->getId(), 'edit_pilot'); ?>"><?php echo $member->getId(); ?></a></td>
            <?php endif; ?>

            <td class="center"><?php echo $member->getFirstname(); ?></td>
            <td class="center"><?php echo $member->getName(); ?></td>
            <td class="center"><?php echo $member->getLicenceNumber()?: '-'; ?></td>
            <td class="center"><?php echo $member->isPilotClassA()? 'X' : '-'; ?></td>
            <td class="center"><?php echo $member->isPilotGaz()? 'X' : '-'; ?></td>
            <td class="center"><?php echo img_picto($member->getReasons(), $member->getIconId(), '', false, false, false, '', 'classfortooltip') ?> </td>
        </tr>
    <?php endforeach; ?>
</table>
